;
; File generated by cc65 v 2.19 - Git 71d64a3
;
	.fopt		compiler,"cc65 v 2.19 - Git 71d64a3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_NMI_flag
	.export		_Frame_Count
	.export		_index
	.export		_joypad1
	.export		_joypad1old
	.export		_joypad1test
	.export		_joypad2
	.export		_joypad2old
	.export		_joypad2test
	.export		_needRedraw
	.export		_state
	.export		_fld
	.export		_x
	.export		_y
	.export		_z
	.export		_field
	.export		_map
	.export		_SPRITES
	.export		_PALETTE
	.export		_All_Off
	.export		_All_On
	.export		_Load_Palette
	.export		_move_logic
	.export		_drawScreen
	.import		_Wait_Vblank
	.import		_UnRLE
	.import		_Get_Input
	.import		_rand
	.import		_srand
	.export		_n1
	.export		_n2
	.export		_n3
	.export		_n4
	.export		_All_Backgrounds
	.export		_putRandom
	.export		_initGame
	.export		_main
	.export		_shiftOne
	.export		_shiftLine
	.export		_fillFldX
	.export		_fillFldY
	.export		_mapField

.segment	"DATA"

_map:
	.word	$0035
	.word	$003B
	.word	$0041
	.word	$0047
	.word	$008D
	.word	$0093
	.word	$0099
	.word	$009F
	.word	$00E5
	.word	$00EB
	.word	$00F1
	.word	$00F7
	.word	$013D
	.word	$0143
	.word	$0149
	.word	$014F
_n2:
	.byte	$0B
	.byte	$00
	.byte	$0B
	.byte	$4D
	.byte	$03
	.byte	$01
	.byte	$05
	.byte	$09
	.byte	$00
	.byte	$0B
	.byte	$31
	.byte	$13
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2C
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2C
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2C
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$15
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$02
	.byte	$3F
	.byte	$03
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$3F
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$3F
	.byte	$19
	.byte	$00
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$29
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$30
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$03
	.byte	$3F
	.byte	$04
	.byte	$05
	.byte	$19
	.byte	$00
	.byte	$03
	.byte	$04
	.byte	$3F
	.byte	$05
	.byte	$19
	.byte	$00
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$3F
	.byte	$19
	.byte	$00
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$29
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$30
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$04
	.byte	$3F
	.byte	$05
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$3F
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$3F
	.byte	$19
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$29
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$2A
	.byte	$14
	.byte	$0B
	.byte	$04
	.byte	$30
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$05
	.byte	$3F
	.byte	$06
	.byte	$07
	.byte	$19
	.byte	$00
	.byte	$05
	.byte	$06
	.byte	$3F
	.byte	$07
	.byte	$19
	.byte	$00
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$3F
	.byte	$19
	.byte	$00
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$19
	.byte	$00
	.byte	$0B
	.byte	$04
	.byte	$1A
	.byte	$00
	.byte	$0B
	.byte	$06
	.byte	$2D
	.byte	$2E
	.byte	$0B
	.byte	$04
	.byte	$2B
	.byte	$2E
	.byte	$0B
	.byte	$04
	.byte	$2B
	.byte	$2E
	.byte	$0B
	.byte	$04
	.byte	$2B
	.byte	$2E
	.byte	$0B
	.byte	$04
	.byte	$2F
	.byte	$00
	.byte	$0B
	.byte	$FE
	.byte	$00
	.byte	$0B
	.byte	$2C
	.byte	$6A
	.byte	$9A
	.byte	$5A
	.byte	$6A
	.byte	$9A
	.byte	$5A
	.byte	$22
	.byte	$88
	.byte	$6A
	.byte	$9A
	.byte	$5A
	.byte	$6A
	.byte	$9A
	.byte	$5A
	.byte	$22
	.byte	$00
	.byte	$6A
	.byte	$9A
	.byte	$5A
	.byte	$6A
	.byte	$9A
	.byte	$5A
	.byte	$22
	.byte	$00
	.byte	$6A
	.byte	$9A
	.byte	$5A
	.byte	$6A
	.byte	$9A
	.byte	$5A
	.byte	$22
	.byte	$00
	.byte	$0A
	.byte	$0B
	.byte	$05
	.byte	$02
	.byte	$0A
	.byte	$00
	.byte	$0B
	.byte	$0D
	.byte	$00
	.byte	$0B
	.byte	$00

.segment	"RODATA"

_PALETTE:
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$0F
	.byte	$01
	.byte	$11
	.byte	$21
	.byte	$0F
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$0F
	.byte	$09
	.byte	$19
	.byte	$38
_n1:
	.byte	$01
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$13
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$A9
	.byte	$21
	.byte	$39
	.byte	$37
	.byte	$40
	.byte	$40
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$31
	.byte	$33
	.byte	$39
	.byte	$31
	.byte	$00
	.byte	$01
	.byte	$70
	.byte	$13
	.byte	$14
	.byte	$01
	.byte	$11
	.byte	$15
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$19
	.byte	$00
	.byte	$1B
	.byte	$00
	.byte	$1C
	.byte	$1D
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$00
	.byte	$21
	.byte	$22
	.byte	$23
	.byte	$24
	.byte	$20
	.byte	$25
	.byte	$1D
	.byte	$26
	.byte	$00
	.byte	$1A
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$19
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$27
	.byte	$28
	.byte	$27
	.byte	$27
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$1A
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$16
	.byte	$17
	.byte	$01
	.byte	$11
	.byte	$18
	.byte	$00
	.byte	$01
	.byte	$44
	.byte	$AA
	.byte	$01
	.byte	$08
	.byte	$26
	.byte	$55
	.byte	$01
	.byte	$03
	.byte	$99
	.byte	$AA
	.byte	$AA
	.byte	$A6
	.byte	$A5
	.byte	$A5
	.byte	$A4
	.byte	$A5
	.byte	$A9
	.byte	$AA
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$0C
	.byte	$0F
	.byte	$0F
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$10
	.byte	$00
	.byte	$01
	.byte	$00
_n3:
	.byte	$01
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$13
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$6A
	.byte	$35
	.byte	$33
	.byte	$36
	.byte	$37
	.byte	$00
	.byte	$32
	.byte	$38
	.byte	$37
	.byte	$39
	.byte	$3F
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$AF
	.byte	$13
	.byte	$14
	.byte	$01
	.byte	$11
	.byte	$15
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$19
	.byte	$00
	.byte	$1B
	.byte	$00
	.byte	$1C
	.byte	$1D
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$00
	.byte	$21
	.byte	$22
	.byte	$23
	.byte	$24
	.byte	$20
	.byte	$25
	.byte	$1D
	.byte	$26
	.byte	$00
	.byte	$1A
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$19
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$27
	.byte	$28
	.byte	$27
	.byte	$27
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$1A
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$16
	.byte	$17
	.byte	$01
	.byte	$11
	.byte	$18
	.byte	$00
	.byte	$01
	.byte	$44
	.byte	$AA
	.byte	$01
	.byte	$08
	.byte	$26
	.byte	$55
	.byte	$01
	.byte	$03
	.byte	$99
	.byte	$AA
	.byte	$AA
	.byte	$A6
	.byte	$A5
	.byte	$A5
	.byte	$A4
	.byte	$A5
	.byte	$A9
	.byte	$AA
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$C0
	.byte	$F0
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$17
	.byte	$00
	.byte	$01
	.byte	$00
_n4:
	.byte	$01
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$12
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$00
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$01
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$12
	.byte	$00
	.byte	$00
	.byte	$12
	.byte	$12
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$13
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$10
	.byte	$11
	.byte	$00
	.byte	$01
	.byte	$6B
	.byte	$3A
	.byte	$32
	.byte	$3B
	.byte	$00
	.byte	$3C
	.byte	$3D
	.byte	$3E
	.byte	$3F
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$B0
	.byte	$13
	.byte	$14
	.byte	$01
	.byte	$11
	.byte	$15
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$19
	.byte	$00
	.byte	$1B
	.byte	$00
	.byte	$1C
	.byte	$1D
	.byte	$1E
	.byte	$1F
	.byte	$20
	.byte	$00
	.byte	$21
	.byte	$22
	.byte	$23
	.byte	$24
	.byte	$20
	.byte	$25
	.byte	$1D
	.byte	$26
	.byte	$00
	.byte	$1A
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$19
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$27
	.byte	$28
	.byte	$27
	.byte	$27
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$1A
	.byte	$00
	.byte	$01
	.byte	$0B
	.byte	$16
	.byte	$17
	.byte	$01
	.byte	$11
	.byte	$18
	.byte	$00
	.byte	$01
	.byte	$44
	.byte	$AA
	.byte	$01
	.byte	$08
	.byte	$26
	.byte	$55
	.byte	$01
	.byte	$03
	.byte	$99
	.byte	$AA
	.byte	$AA
	.byte	$A6
	.byte	$A5
	.byte	$A5
	.byte	$A4
	.byte	$A5
	.byte	$A9
	.byte	$AA
	.byte	$01
	.byte	$08
	.byte	$00
	.byte	$00
	.byte	$C0
	.byte	$F0
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$14
	.byte	$00
	.byte	$01
	.byte	$00
_All_Backgrounds:
	.addr	_n1
	.addr	_n2
	.addr	_n3
	.addr	_n4

.segment	"BSS"

.segment	"ZEROPAGE"
_NMI_flag:
	.res	1,$00
_Frame_Count:
	.res	1,$00
_index:
	.res	1,$00
_joypad1:
	.res	1,$00
_joypad1old:
	.res	1,$00
_joypad1test:
	.res	1,$00
_joypad2:
	.res	1,$00
_joypad2old:
	.res	1,$00
_joypad2test:
	.res	1,$00
_needRedraw:
	.res	1,$00
_state:
	.res	1,$00
_fld:
	.res	4,$00
_x:
	.res	1,$00
_y:
	.res	1,$00
_z:
	.res	1,$00
_field:
	.res	16,$00
.segment	"OAM"
_SPRITES:
	.res	256,$00

; ---------------------------------------------------------------
; void __near__ All_Off (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_Off: near

.segment	"CODE"

;
; PPU_CTRL = 0;
;
	lda     #$00
	sta     $2000
;
; PPU_MASK = 0;
;
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ All_On (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_On: near

.segment	"CODE"

;
; PPU_CTRL = 0x90; // screen is on, NMI on
;
	lda     #$90
	sta     $2000
;
; PPU_MASK = 0x1e;
;
	lda     #$1E
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Load_Palette (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Palette: near

.segment	"CODE"

;
; All_Off();
;
	jsr     _All_Off
;
; PPU_ADDRESS = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	sta     _index
L0007:	lda     _index
	cmp     #$10
	bcs     L0003
;
; PPU_DATA = PALETTE[index];
;
	ldy     _index
	lda     _PALETTE,y
	sta     $2007
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	inc     _index
	jmp     L0007
;
; All_On();
;
L0003:	jmp     _All_On

.endproc

; ---------------------------------------------------------------
; void __near__ move_logic (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_move_logic: near

.segment	"CODE"

;
; Get_Input();
;
	jsr     _Get_Input
;
; if (state == 1) {
;
	lda     _state
	cmp     #$01
	jne     L0045
;
; if (((joypad1 & RIGHT) != 0) && ((joypad1old & RIGHT) == 0)) { // нажали вправо
;
	lda     _joypad1
	and     #$01
	beq     L0036
	lda     _joypad1old
	and     #$01
	bne     L0036
;
; for (index = 0; index < 4; ++index) fillFldY(0, 1, 2, 3, index);
;
	sta     _index
L0035:	lda     _index
	cmp     #$04
	bcs     L000A
	jsr     decsp4
	lda     #$00
	ldy     #$03
	sta     (sp),y
	lda     #$01
	dey
	sta     (sp),y
	tya
	dey
	sta     (sp),y
	lda     #$03
	dey
	sta     (sp),y
	lda     _index
	jsr     _fillFldY
	inc     _index
	jmp     L0035
;
; putRandom();
;
L000A:	jsr     _putRandom
;
; if (((joypad1 & LEFT) != 0) && ((joypad1old & LEFT) == 0)) { // нажали влево
;
L0036:	lda     _joypad1
	and     #$02
	beq     L003B
	lda     _joypad1old
	and     #$02
	bne     L003B
;
; for (index = 0; index < 4; ++index) fillFldY(3, 2, 1, 0, index);
;
	sta     _index
L003A:	lda     _index
	cmp     #$04
	bcs     L0014
	jsr     decsp4
	lda     #$03
	tay
	sta     (sp),y
	lda     #$02
	dey
	sta     (sp),y
	lda     #$01
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	lda     _index
	jsr     _fillFldY
	inc     _index
	jmp     L003A
;
; putRandom();
;
L0014:	jsr     _putRandom
;
; if (((joypad1 & DOWN) != 0) && ((joypad1old & DOWN) == 0)) { // нажали вниз
;
L003B:	lda     _joypad1
	and     #$04
	beq     L0040
	lda     _joypad1old
	and     #$04
	bne     L0040
;
; for (index = 0; index < 4; ++index) fillFldX(0, 1, 2, 3, index);
;
	sta     _index
L003F:	lda     _index
	cmp     #$04
	bcs     L001E
	jsr     decsp4
	lda     #$00
	ldy     #$03
	sta     (sp),y
	lda     #$01
	dey
	sta     (sp),y
	tya
	dey
	sta     (sp),y
	lda     #$03
	dey
	sta     (sp),y
	lda     _index
	jsr     _fillFldX
	inc     _index
	jmp     L003F
;
; putRandom();
;
L001E:	jsr     _putRandom
;
; if (((joypad1 & UP) != 0) && ((joypad1old & UP) == 0)) { // нажали вверх
;
L0040:	lda     _joypad1
	and     #$08
	beq     L0045
	lda     _joypad1old
	and     #$08
	bne     L0045
;
; for (index = 0; index < 4; ++index) fillFldX(3, 2, 1, 0, index);
;
	sta     _index
L0044:	lda     _index
	cmp     #$04
	bcs     L0028
	jsr     decsp4
	lda     #$03
	tay
	sta     (sp),y
	lda     #$02
	dey
	sta     (sp),y
	lda     #$01
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	lda     _index
	jsr     _fillFldX
	inc     _index
	jmp     L0044
;
; putRandom();
;
L0028:	jsr     _putRandom
;
; if (((joypad1 & START) != 0) && ((joypad1old & START) == 0)) {
;
L0045:	lda     _joypad1
	and     #$10
	beq     L0047
	lda     _joypad1old
	and     #$10
	beq     L0048
L0047:	rts
;
; if (state != 1) {
;
L0048:	lda     _state
	cmp     #$01
	beq     L0031
;
; initGame();
;
	jsr     _initGame
;
; state = 1;
;
	lda     #$01
	sta     _state
;
; needRedraw = 1;
;
	sta     _needRedraw
;
; }
;
L0031:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ drawScreen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_drawScreen: near

.segment	"CODE"

;
; All_Off();
;
	jsr     _All_Off
;
; PPU_ADDRESS = 0x20;
;
	lda     #$20
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; if (state == 1) {
;
	tax
	lda     _state
	cmp     #$01
	bne     L0013
;
; z = 0;
;
	txa
	sta     _z
;
; for (y = 0; y <= 3; y++) {
;
	sta     _y
L0010:	lda     _y
	cmp     #$04
	bcs     L0013
;
; for (x = 0; x <= 3; x++) {
;
	lda     #$00
	sta     _x
	tax
L0011:	lda     _x
	cmp     #$04
	bcs     L0012
;
; mapField(field[x][y], map[z]);
;
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     _y
	lda     (ptr1),y
	jsr     pusha
	ldx     #$00
	lda     _z
	asl     a
	bcc     L000E
	inx
	clc
L000E:	adc     #<(_map)
	sta     ptr1
	txa
	adc     #>(_map)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _mapField
;
; z++;
;
	inc     _z
;
; for (x = 0; x <= 3; x++) {
;
	ldx     #$00
	inc     _x
	jmp     L0011
;
; for (y = 0; y <= 3; y++) {
;
L0012:	inc     _y
	jmp     L0010
;
; UnRLE(All_Backgrounds[state]);
;
L0013:	lda     _state
	asl     a
	bcc     L000F
	ldx     #$01
	clc
L000F:	adc     #<(_All_Backgrounds)
	sta     ptr1
	txa
	adc     #>(_All_Backgrounds)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _UnRLE
;
; Wait_Vblank();  // не включаем экран при обратном ходе луча
;
	jsr     _Wait_Vblank
;
; All_On();
;
	jsr     _All_On
;
; needRedraw = 0;
;
	lda     #$00
	sta     _needRedraw
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ putRandom (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_putRandom: near

.segment	"CODE"

;
; x = rand() % 4;
;
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     tosmoda0
	sta     _x
;
; y = rand() % 4;
;
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     tosmoda0
	sta     _y
;
; z = 1;
;
	ldx     #$00
	lda     #$01
	sta     _z
;
; while ((field[x][y] > 0) && (state == 1)) {
;
	jmp     L0012
;
; x = rand() % 4;
;
L0002:	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     tosmoda0
	sta     _x
;
; y = rand() % 4;
;
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     tosmoda0
	sta     _y
;
; z++;
;
	inc     _z
;
; if (z == 16) {
;
	ldx     #$00
	lda     _z
	cmp     #$10
	bne     L0012
;
; state = 2;
;
	lda     #$02
	sta     _state
;
; while ((field[x][y] > 0) && (state == 1)) {
;
L0012:	lda     _x
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     _y
	lda     (ptr1),y
	beq     L0017
	lda     _state
	cmp     #$01
	beq     L0002
;
; if (state == 1) {
;
L0017:	lda     _state
	cmp     #$01
	bne     L0018
;
; if (rand() % 4 == 0) {
;
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     tosmoda0
	cpx     #$00
	bne     L000A
	cmp     #$00
	bne     L0019
;
; field[x][y] = 2;
;
	lda     _x
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     _y
	lda     #$02
;
; else {
;
	jmp     L0011
;
; field[x][y] = 1;
;
L000A:	ldx     #$00
L0019:	lda     _x
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     _y
	lda     #$01
L0011:	sta     (ptr1),y
;
; needRedraw = 1;
;
L0018:	lda     #$01
	sta     _needRedraw
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ initGame (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initGame: near

.segment	"CODE"

;
; srand(Frame_Count);
;
	ldx     #$00
	lda     _Frame_Count
	jsr     _srand
;
; for (y = 0; y <= 3; y++) {
;
	lda     #$00
	sta     _y
L000B:	lda     _y
	cmp     #$04
	bcs     L000E
;
; for (x = 0; x <= 3; x++) {
;
	lda     #$00
	sta     _x
L000C:	lda     _x
	cmp     #$04
	bcs     L000D
;
; field[x][y] = 0x00;
;
	ldx     #$00
	lda     _x
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     _y
	lda     #$00
	sta     (ptr1),y
;
; for (x = 0; x <= 3; x++) {
;
	inc     _x
	jmp     L000C
;
; for (y = 0; y <= 3; y++) {
;
L000D:	inc     _y
	jmp     L000B
;
; state = 1;
;
L000E:	lda     #$01
	sta     _state
;
; putRandom();
;
	jsr     _putRandom
;
; putRandom();
;
	jsr     _putRandom
;
; state = 0;
;
	lda     #$00
	sta     _state
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; initGame();
;
	jsr     _initGame
;
; Load_Palette();
;
	jsr     _Load_Palette
;
; state = 0; // начало игры
;
	lda     #$00
	sta     _state
;
; needRedraw = 1;
;
	lda     #$01
	sta     _needRedraw
;
; while (NMI_flag == 0); 
;
L0009:	lda     _NMI_flag
	beq     L0009
;
; move_logic();
;
	jsr     _move_logic
;
; if (needRedraw != 0) {
;
	lda     _needRedraw
	beq     L000B
;
; drawScreen();
;
	jsr     _drawScreen
;
; NMI_flag = 0;
;
	lda     #$00
L000B:	sta     _NMI_flag
;
; while (1){  
;
	jmp     L0009

.endproc

; ---------------------------------------------------------------
; void __near__ shiftOne (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_shiftOne: near

.segment	"CODE"

;
; if (fld[3] == 0) { fld[3] = fld[2]; fld[2] = 0; }
;
	lda     _fld+3
	bne     L0008
	lda     _fld+2
	sta     _fld+3
	lda     #$00
	sta     _fld+2
;
; if (fld[2] == 0) { fld[2] = fld[1]; fld[1] = 0; }
;
L0008:	lda     _fld+2
	bne     L0009
	lda     _fld+1
	sta     _fld+2
	lda     #$00
	sta     _fld+1
;
; if (fld[1] == 0) { fld[1] = fld[0]; fld[0] = 0; }
;
L0009:	lda     _fld+1
	bne     L000A
	lda     _fld
	sta     _fld+1
	lda     #$00
	sta     _fld
;
; if (fld[3] == 0) { fld[3] = fld[2]; fld[2] = 0; }
;
L000A:	lda     _fld+3
	bne     L000B
	lda     _fld+2
	sta     _fld+3
	lda     #$00
	sta     _fld+2
;
; if (fld[2] == 0) { fld[2] = fld[1]; fld[1] = 0; }
;
L000B:	lda     _fld+2
	bne     L000C
	lda     _fld+1
	sta     _fld+2
	lda     #$00
	sta     _fld+1
;
; if (fld[3] == 0) { fld[3] = fld[2]; fld[2] = 0; }
;
L000C:	lda     _fld+3
	bne     L0007
	lda     _fld+2
	sta     _fld+3
	lda     #$00
	sta     _fld+2
;
; }
;
L0007:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ shiftLine (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_shiftLine: near

.segment	"CODE"

;
; shiftOne();
;
	jsr     _shiftOne
;
; if ((fld[2] == fld[3]) && (fld[2] > 0)) { fld[2]++; fld[3] = 0; if (fld[2] == 11) state = 3; }
;
	lda     _fld+2
	cmp     _fld+3
	bne     L0013
	lda     _fld+2
	beq     L0013
	inc     _fld+2
	lda     #$00
	sta     _fld+3
	lda     _fld+2
	cmp     #$0B
	bne     L0013
	lda     #$03
	sta     _state
;
; if ((fld[1] == fld[2]) && (fld[1] > 0)) { fld[1]++; fld[2] = 0; if (fld[1] == 11) state = 3; }
;
L0013:	lda     _fld+1
	cmp     _fld+2
	bne     L0016
	lda     _fld+1
	beq     L0016
	inc     _fld+1
	lda     #$00
	sta     _fld+2
	lda     _fld+1
	cmp     #$0B
	bne     L0016
	lda     #$03
	sta     _state
;
; if ((fld[0] == fld[1]) && (fld[0] > 0)) { fld[0]++; fld[1] = 0; if (fld[0] == 11) state = 3; } 
;
L0016:	lda     _fld
	cmp     _fld+1
	bne     L0010
	lda     _fld
	beq     L0010
	inc     _fld
	lda     #$00
	sta     _fld+1
	lda     _fld
	cmp     #$0B
	bne     L0010
	lda     #$03
	sta     _state
;
; shiftOne();
;
L0010:	jmp     _shiftOne

.endproc

; ---------------------------------------------------------------
; void __near__ fillFldX (unsigned char n0, unsigned char n1, unsigned char n2, unsigned char n3, unsigned char rw)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fillFldX: near

.segment	"CODE"

;
; void fillFldX(unsigned char n0, unsigned char n1, unsigned char n2, unsigned char n3, unsigned char rw) {
;
	jsr     pusha
;
; fld[0] = field[rw][n0];
;
	ldx     #$00
	lda     (sp,x)
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$04
	lda     (sp),y
	tay
	lda     (ptr1),y
	sta     _fld
;
; fld[1] = field[rw][n1];
;
	ldx     #$00
	lda     (sp,x)
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$03
	lda     (sp),y
	tay
	lda     (ptr1),y
	sta     _fld+1
;
; fld[2] = field[rw][n2];
;
	ldx     #$00
	lda     (sp,x)
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$02
	lda     (sp),y
	tay
	lda     (ptr1),y
	sta     _fld+2
;
; fld[3] = field[rw][n3];
;
	ldx     #$00
	lda     (sp,x)
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$01
	lda     (sp),y
	tay
	lda     (ptr1),y
	sta     _fld+3
;
; shiftLine();
;
	jsr     _shiftLine
;
; field[rw][n0] = fld[0];
;
	ldx     #$00
	lda     (sp,x)
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$04
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0002
	inx
L0002:	sta     ptr1
	stx     ptr1+1
	lda     _fld
	ldy     #$00
	sta     (ptr1),y
;
; field[rw][n1] = fld[1];
;
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$03
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0003
	inx
L0003:	sta     ptr1
	stx     ptr1+1
	lda     _fld+1
	ldy     #$00
	sta     (ptr1),y
;
; field[rw][n2] = fld[2];
;
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$02
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0004
	inx
L0004:	sta     ptr1
	stx     ptr1+1
	lda     _fld+2
	ldy     #$00
	sta     (ptr1),y
;
; field[rw][n3] = fld[3];
;
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	iny
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0005
	inx
L0005:	sta     ptr1
	stx     ptr1+1
	lda     _fld+3
	dey
	sta     (ptr1),y
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ fillFldY (unsigned char n0, unsigned char n1, unsigned char n2, unsigned char n3, unsigned char rw)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fillFldY: near

.segment	"CODE"

;
; void fillFldY(unsigned char n0, unsigned char n1, unsigned char n2, unsigned char n3, unsigned char rw) {
;
	jsr     pusha
;
; fld[0] = field[n0][rw];
;
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	tay
	lda     (ptr1),y
	sta     _fld
;
; fld[1] = field[n1][rw];
;
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	tay
	lda     (ptr1),y
	sta     _fld+1
;
; fld[2] = field[n2][rw];
;
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	tay
	lda     (ptr1),y
	sta     _fld+2
;
; fld[3] = field[n3][rw];
;
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	dey
	lda     (sp),y
	tay
	lda     (ptr1),y
	sta     _fld+3
;
; shiftLine();
;
	jsr     _shiftLine
;
; field[n0][rw] = fld[0];
;
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0002
	inx
L0002:	sta     ptr1
	stx     ptr1+1
	lda     _fld
	sta     (ptr1),y
;
; field[n1][rw] = fld[1];
;
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0003
	inx
L0003:	sta     ptr1
	stx     ptr1+1
	lda     _fld+1
	sta     (ptr1),y
;
; field[n2][rw] = fld[2];
;
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0004
	inx
L0004:	sta     ptr1
	stx     ptr1+1
	lda     _fld+2
	sta     (ptr1),y
;
; field[n3][rw] = fld[3];
;
	iny
	ldx     #$00
	lda     (sp),y
	jsr     aslax2
	clc
	adc     #<(_field)
	sta     ptr1
	txa
	adc     #>(_field)
	sta     ptr1+1
	dey
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0005
	inx
L0005:	sta     ptr1
	stx     ptr1+1
	lda     _fld+3
	sta     (ptr1),y
;
; }
;
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ mapField (unsigned char n, int adr)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mapField: near

.segment	"CODE"

;
; void mapField(unsigned char n, int adr) {
;
	jsr     pushax
;
; n2[adr]   = 0x00;
;
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	tya
	sta     (ptr1),y
;
; n2[adr+1] = 0x00;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L0028
	inx
	clc
L0028:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	tya
	sta     (ptr1),y
;
; n2[adr+2] = 0x00;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0029
	inx
	clc
L0029:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	tya
	sta     (ptr1),y
;
; n2[adr+3] = 0x00;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L002A
	inx
	clc
L002A:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	tya
	sta     (ptr1),y
;
; if (n == 1) { 
;
	ldy     #$02
	lda     (sp),y
	cmp     #$01
	bne     L0044
;
; n2[adr + 3] = 0x03; 
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L002B
	inx
	clc
L002B:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$03
	sta     (ptr1),y
;
; if (n == 2) { 
;
	ldy     #$02
L0044:	lda     (sp),y
	cmp     #$02
	bne     L0046
;
; n2[adr + 3] = 0x05; 
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L002C
	inx
	clc
L002C:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$05
	sta     (ptr1),y
;
; if (n == 3) { 
;
	ldy     #$02
L0046:	lda     (sp),y
	cmp     #$03
	bne     L0048
;
; n2[adr + 3] = 0x09; 
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L002D
	inx
	clc
L002D:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$09
	sta     (ptr1),y
;
; if (n == 4) { 
;
	ldy     #$02
L0048:	lda     (sp),y
	cmp     #$04
	bne     L004A
;
; n2[adr + 2] = 0x02;
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L002E
	inx
	clc
L002E:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$02
	sta     (ptr1),y
;
; n2[adr + 3] = 0x07;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L002F
	inx
	clc
L002F:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$07
	sta     (ptr1),y
;
; if (n == 5) {
;
	ldy     #$02
L004A:	lda     (sp),y
	cmp     #$05
	bne     L004C
;
; n2[adr + 2] = 0x04;
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0030
	inx
	clc
L0030:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$04
	sta     (ptr1),y
;
; n2[adr + 3] = 0x03;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L0031
	inx
	clc
L0031:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$03
	sta     (ptr1),y
;
; if (n == 6) { 
;
	ldy     #$02
L004C:	lda     (sp),y
	cmp     #$06
	bne     L004E
;
; n2[adr + 2] = 0x07;
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0032
	inx
	clc
L0032:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$07
	sta     (ptr1),y
;
; n2[adr + 3] = 0x05;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L0033
	inx
	clc
L0033:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$05
	sta     (ptr1),y
;
; if (n == 7) { 
;
	ldy     #$02
L004E:	lda     (sp),y
	cmp     #$07
	bne     L0050
;
; n2[adr + 1] = 0x02;
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L0034
	inx
	clc
L0034:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$02
	sta     (ptr1),y
;
; n2[adr + 2] = 0x03;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0035
	inx
	clc
L0035:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$03
	sta     (ptr1),y
;
; n2[adr + 3] = 0x09;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L0036
	inx
	clc
L0036:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$09
	sta     (ptr1),y
;
; if (n == 8) { 
;
	ldy     #$02
L0050:	lda     (sp),y
	cmp     #$08
	bne     L0052
;
; n2[adr + 1] = 0x03;
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L0037
	inx
	clc
L0037:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$03
	sta     (ptr1),y
;
; n2[adr + 2] = 0x06;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0038
	inx
	clc
L0038:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$06
	sta     (ptr1),y
;
; n2[adr + 3] = 0x07;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L0039
	inx
	clc
L0039:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$07
	sta     (ptr1),y
;
; if (n == 9) { 
;
	ldy     #$02
L0052:	lda     (sp),y
	cmp     #$09
	bne     L0054
;
; n2[adr + 1] = 0x06;
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L003A
	inx
	clc
L003A:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$06
	sta     (ptr1),y
;
; n2[adr + 2] = 0x02;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L003B
	inx
	clc
L003B:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$02
	sta     (ptr1),y
;
; n2[adr + 3] = 0x03;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L003C
	inx
	clc
L003C:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$03
	sta     (ptr1),y
;
; if (n == 10) { 
;
	ldy     #$02
L0054:	lda     (sp),y
	cmp     #$0A
	bne     L0056
;
; n2[adr] = 0x02;
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$02
	sta     (ptr1),y
;
; n2[adr + 1] = 0x01;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L003D
	inx
	clc
L003D:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$01
	sta     (ptr1),y
;
; n2[adr + 2] = 0x03;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L003E
	inx
	clc
L003E:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$03
	sta     (ptr1),y
;
; n2[adr + 3] = 0x05;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L003F
	inx
	clc
L003F:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$05
	sta     (ptr1),y
;
; if (n == 11) {
;
	ldy     #$02
L0056:	lda     (sp),y
	cmp     #$0B
	bne     L0024
;
; n2[adr] = 0x03;
;
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$03
	sta     (ptr1),y
;
; n2[adr + 1] = 0x01;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L0040
	inx
	clc
L0040:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$01
	sta     (ptr1),y
;
; n2[adr + 2] = 0x05;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$02
	bcc     L0041
	inx
	clc
L0041:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$05
	sta     (ptr1),y
;
; n2[adr + 3] = 0x09;
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$03
	bcc     L0042
	inx
	clc
L0042:	adc     #<(_n2)
	sta     ptr1
	txa
	adc     #>(_n2)
	sta     ptr1+1
	lda     #$09
	sta     (ptr1),y
;
; }
;
L0024:	jmp     incsp3

.endproc

